services:
  postgres:
    image: postgres:16
    container_name: weather_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-weather}
      POSTGRES_USER: ${POSTGRES_USER:-weather}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-weather}
      TZ: ${POSTGRES_TZ:-UTC}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./resources/sql/pg/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-weather} -d ${POSTGRES_DB:-weather}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
